### ISSUE TITLE
item的点击事件容易被误触发。比如套在FlatList上，下拉刷新时，如果手指在item事件触控区域，下拉松开后会触发item内的点击事件【Android 】

### ISSUE THREAD

**Issue by fish19920404** [sdcxtech/react-native-troika#11]

**Comment by listenzz** [comment]
你好，当下拉时，点击时间会被取消。如下面使用 `TouchableHighlight` 那样。

![ezgif com-video-to-gif](https://github.com/sdcxtech/react-native-troika/assets/4386370/1cc29989-c423-465c-82b7-56b5555696e9)

**Comment by listenzz** [comment]
经检测，iOS 有类似问题，已经处理。

**Comment by fish19920404** [comment]
您好，我使用了TouchableHighlight 取包裹点击事件，这边最后还是会被执行，..... 下拉完成后，你那边click方法没有日志打印？

**Comment by listenzz** [comment]
> 您好，我使用了TouchableHighlight 取包裹点击事件，这边最后还是会被执行，..... 下拉完成后，你那边click方法没有日志打印？

如果有执行，右边的数字会 + 1

**Comment by fish19920404** [comment]
群主是在真机上调试的吗？

**Comment by listenzz** [comment]
> 群主是在真机上调试的吗？

真机试过的。

**Comment by fish19920404** [comment]
https://github.com/sdcxtech/react-native-troika/assets/16273753/58aef277-9393-406e-adc2-01fd79e59536

<View style={{ flex: 1, marginTop: 60 }}>
      <PullToRefresh
        header={<TestSpinnerPullToRefreshHeader refreshing={refreshing} onRefresh={beginRefresh} />}
        footer={
          <SpinnerPullToRefreshFooter manual refreshing={loadingMore} noMoreData={noMoreData} />
        }
        loadingMore={loadingMore}>
        <FlatList
          data={[1, 3, 4, 5, 6, 7, 8, 9, 10, 11]}
          keyExtractor={(item, index) => index.toString()}
          showsVerticalScrollIndicator={false}
          showsHorizontalScrollIndicator={false}
          renderItem={({ item, index }) => (
            <TouchableHighlight style={{ height: 40 }} underlayColor='#DDDDDD' onPress={testItem}>
              <Text>我是{index}</Text>
            </TouchableHighlight>
          )}
          keyboardShouldPersistTaps='handled'
        />
      </PullToRefresh>
    </View>

如下是相关测试代码，麻烦帮忙看下哈

**Comment by fish19920404** [comment]
<View style={{ flex: 1, marginTop: 60 }}>
      <PullToRefresh
        header={<TestSpinnerPullToRefreshHeader refreshing={refreshing} onRefresh={beginRefresh} />}
        footer={
          <SpinnerPullToRefreshFooter manual refreshing={loadingMore} noMoreData={noMoreData} />
        }
        loadingMore={loadingMore}>
        <FlatList
          data={[1, 3, 4, 5, 6, 7, 8, 9, 10, 11]}
          keyExtractor={(item, index) => index.toString()}
          showsVerticalScrollIndicator={false}
          showsHorizontalScrollIndicator={false}
          renderItem={({ item, index }) => (
            <TouchableHighlight style={{ height: 40 }} underlayColor='#DDDDDD' onPress={testItem}>
              <Text>我是{index}</Text>
            </TouchableHighlight>
          )}
          keyboardShouldPersistTaps='handled'
        />
      </PullToRefresh>
    </View>

TestSpinnerPullToRefreshHeader 就是您测试demo里的类，我这边改了下名字

**Comment by listenzz** [comment]
你没有开启 `nestedScrollEnabled`

**Comment by fish19920404** [comment]
可以了，谢谢～
