### ISSUE TITLE
Android 当嵌套的 List 长度不够一屏的时候，不能下拉刷新了

### ISSUE THREAD

**Issue by yupengyang** [sdcxtech/react-native-troika#13]
比如我嵌套一个 FlatList，但是接口返回数据为空，我展示一个 EmptyView，这个时候下拉刷新不生效了

**Comment by listenzz** [comment]
请问这个 `EmptyVeiw` 是放在哪？给个能复现的 demo?

**Comment by luyuan11233** [comment]
嵌套在NestScrollView下的
import { RefreshControl } from '@sdcx/pull-to-refresh';
<FlashList
          nestedScrollEnabled
          bounces={false}
          ListEmptyComponent={<EmptyView />}
          ListFooterComponent={<View style={{ height: getBottomHegiht() }} />}
          data={isShowSearch ? showSearchList : list}
          onEndReachedThreshold={pageList.onEndReachedThreshold}
          onEndReached={loadMore}
          refreshControl={
            <RefreshControl
              onRefresh={refresh}
              refreshing={refreshing}
              progressBackgroundColor={theme.fill.primary}
              colors={[theme.system.bluePrimary]}
            />
          }
          renderItem={({ item }) => <DirectCommissionCell item={item} />}
          estimatedItemSize={10}
        />
      </View>
      
      当滑动到最顶上的时候，在下拉回来，发现触发发不了下拉刷新

**Comment by luyuan11233** [comment]
```
这边是比较完整的代码
<View style={[styles.container, styles.bg]}>

<NestedScrollViewHeader
onScroll={onScroll}
stickyHeaderBeginIndex={1}
stickyHeight={naviHeight + kTabBarHeight}>
<Text>
我是吸顶title
</Text>
<TabBar
tabs={pages}
onTabPress={setPage}
position={position}
offset={offset}
page={page}
isIdle={isIdle}
indicatorStyle={styles.indicator}
labelStyle={[fonts.regular.subHeadline2, commonStyles.textTertiary]}
labelSelectStyle={[fonts.medium.subHeadline2, commonStyles.textPrimary]}
/>

其中一个PageViews代码为

const AffiliateB=()=>{
return
<FlashList
      data={isShowSearch ? showSearchList : list}
      onEndReachedThreshold={pageList.onEndReachedThreshold}
      onEndReached={loadMore}
      refreshControl={
        <RefreshControl
          onRefresh={refresh}
          refreshing={refreshing}
          progressBackgroundColor={theme.fill.primary}
          colors={[theme.system.bluePrimary]}
        />
      }
      nestedScrollEnabled
      ListEmptyComponent={<EmptyView />}
      ListFooterComponent={<View style={{ height: getBottomHegiht() }} />}
      renderItem={({ item, index }) => <Text>123</Text>}
      estimatedItemSize={10}
    />
}
```

**Comment by luyuan11233** [comment]
[test.zip](https://github.com/sdcxtech/react-native-troika/files/12673918/test.zip)

压缩文件里是简易的代码代码

**Comment by luyuan11233** [comment]
这是我的空页面
const EmptyView = ({ emptyStyle }: EmptyViewProps) => {
  const styles = useStyles();
  const { t } = useTranslation();

  return (
    <View style={[styles.container, styles.column, styles.alignCenter, styles.top_100, emptyStyle]}>
    <IconEmpty width={72} height={72} />
      <Text style={[styles.top_24, styles.textPrimary, fonts.regular.caption1]}>
        {t('common.list_empty_msg')}
      </Text>
    </View>
  );
};

**Comment by listenzz** [comment]
大哥，你弄个直接能跑的给我，不是更省事吗？

**Comment by listenzz** [comment]
`FlashList` 貌似不支持 `ListEmptyComponent` 属性

**Comment by listenzz** [comment]
已经处理，升级 @sdcx/pull-to-refresh 到 0.13.0 即可

**Comment by luyuan11233** [comment]
才看到，大佬已经解决了，很赞
不过默认的确实很丑,给个建议，可以把以下的都加一下，因为我发现怎么布局 都感觉有点丑 hh
implementation  'io.github.scwang90:refresh-layout-kernel:2.0.6'      //核心必须依赖
implementation  'io.github.scwang90:refresh-header-classics:2.0.6'    //经典刷新头
implementation  'io.github.scwang90:refresh-header-radar:2.0.6'       //雷达刷新头
implementation  'io.github.scwang90:refresh-header-falsify:2.0.6'     //虚拟刷新头
implementation  'io.github.scwang90:refresh-header-material:2.0.6'    //谷歌刷新头
implementation  'io.github.scwang90:refresh-header-two-level:2.0.6'   //二级刷新头
implementation  'io.github.scwang90:refresh-footer-ball:2.0.6'        //球脉冲加载
implementation  'io.github.scwang90:refresh-footer-classics:2.0.6'    //经典加载

**Comment by luyuan11233** [comment]
再次感谢大佬
