### ISSUE TITLE
NestedScrollView在安卓上滚动手势不连贯，会在吸顶的地方卡着

### ISSUE THREAD

**Issue by yanhongchang-1105** [sdcxtech/react-native-troika#15]
NestedScrollView在安卓上滚动手势不连贯，会在吸顶的地方卡着

**Comment by listenzz** [comment]
这个动作叫 fling(甩)，在 Android 上表现就是这样的，虽然和 iOS 不一致。可以找一些 Android App 来看。

**Comment by yanhongchang-1105** [comment]
stickyHeight在安卓和ios上吸顶的表现高度不一致

**Comment by yanhongchang-1105** [comment]
<img width="395" alt="image" src="https://github.com/sdcxtech/react-native-troika/assets/72793045/0918db80-decc-468a-b45f-a0137105f85f">

**Comment by yanhongchang-1105** [comment]
![image](https://github.com/sdcxtech/react-native-troika/assets/72793045/22a39e77-1055-4257-a336-ccbbd4f76844)
代码：
`  <View style={{flex: 1, paddingTop: insets.top, backgroundColor: '#fff'}}>
            {/* <FixedAbilityCard /> */}
            <NestedScrollView>
                <NestedScrollViewHeader stickyHeaderBeginIndex={1} stickyHeight={100 + insets.top}>
                    <View style={{backgroundColor: 'yellow', height: 100}} />
                    <Tabbar setPage={setPage} current={current} />
                </NestedScrollViewHeader>
                <PagerView
                    ref={pagerViewRef}
                    onPageSelected={(e) => {
                        setCurrent(e.nativeEvent.position);
                    }}>
                    <ScrollView
                        nestedScrollEnabled
                        onScroll={(e) => {
                            console.log(e);
                        }}>
                        <Button onPress={() => navigation.navigate('LiveList')} title="直播列表" />

                        <View style={{height: 3000, backgroundColor: 'red'}} />
                    </ScrollView>
                    <ScrollView nestedScrollEnabled>
                        <View style={{height: 3000, backgroundColor: '#0f0'}} />
                    </ScrollView>
                </PagerView>
            </NestedScrollView>
        </View>`

**Comment by yanhongchang-1105** [comment]
`  <View style={{flex: 1, paddingTop: insets.top, backgroundColor: '#fff'}}>
            <NestedScrollView>
                <NestedScrollViewHeader stickyHeaderBeginIndex={1} stickyHeight={100 + insets.top}>
                    <View style={{backgroundColor: 'yellow', height: 100}} />
                    <Tabbar setPage={setPage} current={current} />
                </NestedScrollViewHeader>
                <PagerView
                    ref={pagerViewRef}
                    onPageSelected={(e) => {
                        setCurrent(e.nativeEvent.position);
                    }}>
                    <ScrollView
                        nestedScrollEnabled
                        onScroll={(e) => {
                            console.log(e);
                        }}>
                        <Button onPress={() => navigation.navigate('LiveList')} title="直播列表" />

                        <View style={{height: 3000, backgroundColor: 'red'}} />
                    </ScrollView>
                    <ScrollView nestedScrollEnabled>
                        <View style={{height: 3000, backgroundColor: '#0f0'}} />
                    </ScrollView>
                </PagerView>
            </NestedScrollView>
        </View>`

**Comment by yanhongchang-1105** [comment]
`
<View style={{flex: 1, paddingTop: insets.top, backgroundColor: '#fff'}}>
            <NestedScrollView>
                <NestedScrollViewHeader stickyHeaderBeginIndex={1} stickyHeight={100 + insets.top}>
                    <View style={{backgroundColor: 'yellow', height: 100}} />
                    <Tabbar setPage={setPage} current={current} />
                </NestedScrollViewHeader>
                <PagerView
                    ref={pagerViewRef}
                    onPageSelected={(e) => {
                        setCurrent(e.nativeEvent.position);
                    }}>
                    <ScrollView
                        nestedScrollEnabled
                        onScroll={(e) => {
                            console.log(e);
                        }}>
                        <Button onPress={() => navigation.navigate('LiveList')} title="直播列表" />

                        <View style={{height: 3000, backgroundColor: 'red'}} />
                    </ScrollView>
                    <ScrollView nestedScrollEnabled>
                        <View style={{height: 3000, backgroundColor: '#0f0'}} />
                    </ScrollView>
                </PagerView>
            </NestedScrollView>
        </View>
`

**Comment by yanhongchang-1105** [comment]
这种布局 当设置stickheight为0时的，安卓tab滚到看不到了 ios位置正确
使用stickyHeaderBeginIndex时正常
但是我需要控制吸顶的高度

**Comment by listenzz** [comment]
看得不是很明白，录个屏或者提供个 demo。

**Comment by listenzz** [comment]
你是不是同时设置了 `stickyHeight ` 和 `stickyHeaderBeginIndex`，并且希望当 `stickyHeight` 为 0 时，`stickyHeaderBeginIndex` 生效？

**Comment by yanhongchang-1105** [comment]
倒是同时设置了 我看文档写的stickyHeight优先级高，就没去掉stickyHeaderBeginIndex
我是想通过stickyHeight来控制吸顶高度，但是发现安卓ios吸顶的位置有误差

**Comment by listenzz** [comment]
可以将 `stickyHeight ` 设置为 `-1` 或者 `undefined`。因为 Android 部分的作者认为设置为 0 也算设置了。

**Comment by yanhongchang-1105** [comment]
博主 又发现个问题，使用NestedScrollView，当tab吸顶了之后，滑动其中一个tabA下的srcollview到一段距离，然后切换另一个tabB，上滑页面让tab不吸顶，此时再切换到tabA,这时候A的scrollview没有自动滚动到顶部，也就是此时内部A的scollview和外部NestedScrollView都可以滚动，这个应该怎么处理？（预期是当不吸顶的时候，滑动的外部的，内部的自动回到顶部）

**Comment by listenzz** [comment]
> 博主 又发现个问题，使用NestedScrollView，当tab吸顶了之后，滑动其中一个tabA下的srcollview到一段距离，然后切换另一个tabB，上滑页面让tab不吸顶，此时再切换到tabA,这时候A的scrollview没有自动滚动到顶部，也就是此时内部A的scollview和外部NestedScrollView都可以滚动，这个应该怎么处理？（预期是当不吸顶的时候，滑动的外部的，内部的自动回到顶部）

自动回到顶部是不正常的。如果你有需要，当切换tab时，把前一个scrollview 通过编码的方式回到顶部即可

**Comment by yanhongchang-1105** [comment]
ok，那自己操作吧

**Comment by yanhongchang-1105** [comment]
兄弟我试了安卓ios三个手机，使用stickyHeight为状态栏高度+头部的高度，三个手机吸顶距离都不一样，炸了...
看你三天前更新了0.12，说统一安卓ios的stickyHeight，有测试这个吗
没更新之前也不一致

**Comment by yanhongchang-1105** [comment]
![781698398694_ pic](https://github.com/sdcxtech/react-native-troika/assets/72793045/6ed3de31-4eeb-4155-896f-a363c035655b)
![771698398383_ pic](https://github.com/sdcxtech/react-native-troika/assets/72793045/deb64b8a-1c7c-43b9-a16a-86dca4ed30d4)
![761698398319_ pic](https://github.com/sdcxtech/react-native-troika/assets/72793045/24ec78c1-bf60-4b13-8f07-0dbeb3dd06df)

**Comment by yanhongchang-1105** [comment]
这么设置的 stickyHeight={insets.top + FixedAbilityCard.Height}
   insets是const insets = useSafeAreaInsets();

**Comment by listenzz** [comment]
请问 `FixedAbilityCard.Height` 是怎么计算的

**Comment by yanhongchang-1105** [comment]
<img width="499" alt="image" src="https://github.com/sdcxtech/react-native-troika/assets/72793045/93bb3445-b250-49f4-be20-90f2f1fcdb9d">

**Comment by listenzz** [comment]
提供一个可直接运行的 demo 给我吧

**Comment by yanhongchang-1105** [comment]
奥 我知道了 不应该加上状态栏的高度，应该是tab的高度

**Comment by listenzz** [comment]
> 奥 我知道了 不应该加上状态栏的高度，应该是tab的高度

嗯嗯，这个 issue 先关了，发现新问题请再开一个。
