### ISSUE TITLE
Is PullToRefresh too high in rn0.72.4

### ISSUE THREAD

**Issue by 16638964387** [sdcxtech/react-native-troika#17]

**Comment by 16638964387** [comment]
<ScrollView
        style={{height: 100 % -tabBarHeight}}
        alwaysBounceHorizontal={false}
        alwaysBounceVertical={false}
        onScroll={onMomentumScrollEnd}
        ref={e => (scollTo = e)}
        refreshControl={
          <PullToRefresh
            refreshing={refreshing}
            onRefresh={() => {
              onRefresh();
            }}
          />  
          
          
          Dropdown refresh masking view

**Comment by listenzz** [comment]
你好，给个图看看？

**Comment by 16638964387** [comment]
@listenzz 
![7c198e39cc262a2aed4c466b9e31c98](https://github.com/sdcxtech/react-native-troika/assets/109561878/41ebad3d-2c5c-4376-b73e-af814e58ac19)
![Uploading f6dfa4432d65e929b8f1211ea16c609.jpg…]()

**Comment by 16638964387** [comment]
![f6dfa4432d65e929b8f1211ea16c609](https://github.com/sdcxtech/react-native-troika/assets/109561878/68e12ae3-06d7-4d65-b314-3f59fca10a89)

**Comment by 16638964387** [comment]
@listenzz 会遮挡部分视图

**Comment by listenzz** [comment]
`ScrollView` 外面的容器是 react-native-pager-view 吗？如果不是，给它添加 `overflow='hidden'` 属性

**Comment by listenzz** [comment]
> `ScrollView` 外面的容器是 react-native-pager-view 吗？如果不是，给它添加 `overflow='hidden'` 属性

应该是 `{ overflow: 'hidden' }` style

**Comment by 16638964387** [comment]
好的，已解决
