### ISSUE TITLE
当scollView不够填满当前屏幕时无法下拉刷新？

### ISSUE THREAD

**Issue by 16638964387** [sdcxtech/react-native-troika#19]
<View style={{flex: 1, overflow: 'hidden', borderWidth: 1}}>
        <ScrollView
          style={{
            height: 100 % -tabBarHeight,
            position: 'relative',
            borderWidth: 1,
            borderColor: 'red',
          }}
          alwaysBounceHorizontal={false}
          alwaysBounceVertical={false}
          onScroll={onMomentumScrollEnd}
          ref={scrollViewRef}
          refreshControl={
            < PullToRefresh refreshing={refreshing} onRefresh={onRefresh} />
 }>
![2c09c2919fed268bd01211a825ac379](https://github.com/sdcxtech/react-native-troika/assets/109561878/2e3b91f6-beae-4472-9ccb-527410b20b98)

**Comment by listenzz** [comment]
应该是可以的，之前修复过这个问题。

**Comment by listenzz** [comment]
`ScrollView` 要设置 `nestedScrollEnabled` 属性，传递给  refreshControl 属性的应该是 RefreshControl 而不是 PullToRefresh。最新版本可以移除 `overflow: 'hidden'` 了。

**Comment by 16638964387** [comment]
> `ScrollView`要设置`nestedScrollEnabled`属性，传递给refreshControl属性的应该是RefreshControl而不是PullToRefresh。最新版本可以移除`overflow: 'hidden'`了。

感谢设置nestedScrollEnabled后可以了
