### ISSUE TITLE
嵌套滚动惯性问题

### ISSUE THREAD

**Issue by changyuwu** [sdcxtech/react-native-troika#20]
嵌套滚动时，子scrollview向下拉动通过惯性滚动到顶部时，NestedScrollViewHeader不会通过惯性出现，需要在向下拉一下才行。demo中就能复现。请问这个问题有解吗？页面是 NestedScroll->NestedScroll + ParallaxHeader

**Comment by changyuwu** [comment]
https://github.com/sdcxtech/react-native-troika/assets/22142838/dfb1518f-6089-4c91-84dc-f7e34d73445e

**Comment by listenzz** [comment]
有解，有些复杂便是。

iOS 无此问题。

**Comment by changyuwu** [comment]
请问android有计划支持吗？或者能否给个思路

**Comment by listenzz** [comment]
重写 `com.reactnative.nestedscroll.NestedScrollView` 的 `onNestedPreScroll` 方法，让 target 发起嵌套滚动，变 fling 为 scroll。这个过程需要借助 Scroller 等辅助类，以及重写 `NestedScrollView` 的 `computeScroll` 方法。

**Comment by listenzz** [comment]
@changyuwu  可以查看这个分支 https://github.com/sdcxtech/react-native-troika/tree/fling-2

**Comment by listenzz** [comment]
> 请问android有计划支持吗？或者能否给个思路

0.14.0 已发布支持
