### ISSUE TITLE
有expo的解决方案吗?

### ISSUE THREAD

**Issue by 418442040** [sdcxtech/react-native-troika#22]
我项目是expo搭建的,我安装了依赖,ios报错找不到依赖,因为我在expo里面没办法执行 pod install?

**Comment by 418442040** [comment]
好的,依然谢谢你为rn做出的贡献

**Comment by 16638964387** [comment]
可以尝试一下  https://docs.expo.dev/workflow/customizing/

**Comment by 418442040** [comment]
> 可以尝试一下 https://docs.expo.dev/workflow/customizing/

太酷啦!谢谢你让我对expo有了更进一步的了解

**Comment by god-zhang** [comment]
没太看懂需要怎么做才能在expo项目中使用, 请问下有具体的操作步骤吗, 非常感谢

**Comment by divineniiquaye** [comment]
I tried the pull to refresh package on an expo porject and it works fine, I just deleted my ios folder and rebuild

**Comment by 418442040** [comment]
> 没太看懂需要怎么做才能在expo项目中使用, 请问下有具体的操作步骤吗, 非常感谢 @418442040

不好意思,现在才看到,expo要使用此库,可以npx expo run android 或者 npx expo run ios
