### ISSUE TITLE
在ios中下拉刷新出现错误

### ISSUE THREAD

**Issue by 16638964387** [sdcxtech/react-native-troika#23]
Exception thrown while executing UI block: RCTScrollView may only contain a single subview, the already set subview looks like: <RNPullToRefresh: 0x121047600; frame = (0 0; 0 0); layer = <CALayer: 0x2813bb000>>
把项目的PullToRefresh组件注释就好了
      <ScrollView
        style={{height: 100 % -tabBarHeight, position: 'relative'}}
        alwaysBounceHorizontal={false}
        alwaysBounceVertical={false}
        nestedScrollEnabled
        onScroll={onMomentumScrollEnd}
        ref={e => (scollTo = e)}
        // refreshControl={
        //   <PullToRefresh
        //     refreshing={refreshing}
        //     onRefresh={() => {
        //       if (cityQuery.default) {
        //         onRefresh({provinceName: location});
        //       } else {
        //         onRefresh();
        //       }
        //     }}
        //   />
        // }
      >

**Comment by listenzz** [comment]
当作为参数传递给 `refreshControl` 时，使用 `RefreshControl` 而不是 `PullToRefresh`.

```ts
import { RefreshControl } from '@sdcx/pull-to-refresh'
```

**Comment by 16638964387** [comment]
> 当作为参数提交时`refreshControl`，使用`RefreshControl`而不是`PullToRefresh`。
> 
> ```ts
> import { RefreshControl } from '@sdcx/pull-to-refresh'
> ```
好的 感谢
