### ISSUE TITLE
使用KeyboardInsetsView会遮挡自定义Custom

### ISSUE THREAD

**Issue by TallNutAlt** [sdcxtech/react-native-troika#25]
![101704679267_ pic](https://github.com/sdcxtech/react-native-troika/assets/109561878/2a7541de-07f3-4a3e-8815-814310d6906b)
这种情况怎么解决呢，头部是一个view没有使用定位的Custom

**Comment by chj-damon** [comment]
代码发来看看

**Comment by TallNutAlt** [comment]
> 代码发来看看

就正常的自定义Custom。 被遮挡了

**Comment by TallNutAlt** [comment]
<View>
      <View
        style={{
          height: StatusBarManager.HEIGHT + 40,
          backgroundColor: props.bgColor,
          paddingLeft: 20,
          paddingBottom: 10,
          paddingRight: 20,
          justifyContent: 'space-between',
          alignItems: 'flex-end',
          flexDirection: 'row',
          borderBottomWidth: props.borderWidth,
          borderColor: props.borderColor ? props.borderColor : 'transparent',
        }}>
        <View
          style={{flexDirection: 'row', width: '25%', alignItems: 'flex-end'}}>
          {props.backIs !== 'none' && (
            <TouchableOpacity
              activeOpacity={0.5}
              onPress={() => {
                if (props.backClick) {
                  props.backClick();
                  return;
                }
                herf.goBack();
              }}>
              <View style={{width: scale(18), height: scale(18)}}>
                {props.ico === 'white' ? (
                  <Image
                    style={{width: scale(8), height: scale(18)}}
                    source={require('../static/image/whiteyoujiantou.png')}
                  />
                ) : (
                  <Image
                    style={{width: scale(8), height: scale(18)}}
                    source={require('../static/image/blackzuojiantou.png')}
                  />
                )}
              </View>
            </TouchableOpacity>
          )}
          <Text
            style={{
              paddingLeft: 5,
              fontSize: props.backTitleFontSize,
              color: props.backTitleColor,
            }}>
            {props.backTitle}
          </Text>
        </View>
        <View style={{minWidth: '25%'}}>
          <Text
            style={{
              fontSize: props.titleFontSize,
              color: props.titleColor,
              textAlign: 'center',
              fontWeight: props.titleFontWeight,
            }}>
            {props.title}
          </Text>
        </View>
        <View style={{width: '25%'}}>
          <Text style={{textAlign: 'right'}}>{props.right}</Text>
        </View>
      </View>
    </View>
自定义Custom的代码

**Comment by TallNutAlt** [comment]
y
