### ISSUE TITLE
ios 键盘弹起时输入框会弹跳一下

### ISSUE THREAD

**Issue by GuoMeng6** [sdcxtech/react-native-troika#49]
ios 在使用 keyboard-insets 组件时，当键盘弹起时，输入框会弹跳一下，紧接着贴合在键盘上，这个有人遇到过吗。运行了 demo 的程序也是这样，具体可查看录屏

https://github.com/user-attachments/assets/6dcd4198-c0b8-447d-b40e-38aa001e2ed1

当前依赖配置信息如下：
"react": "18.2.0",
"react-native": "0.72.0",
"@sdcx/keyboard-insets": "^0.6.0",
"react-native-safe-area-context": "4.5.0",

**Comment by listenzz** [comment]
ios 18?

**Comment by GuoMeng6** [comment]
> ios 18?

用的是 iOS 17.4 虚拟机 iphone 15 Pro

真机 iphone 14 Pro， iOS 17.6.1 也是这个现象

**Comment by listenzz** [comment]
你是把 demo 放到自己的项目里面跑了吗？

**Comment by GuoMeng6** [comment]
> 你是把 demo 放到自己的项目里面跑了吗？

是的，我发现使用 KeyboardAvoidingView、KeyboardAwareScrollView 也会有同样的问题

**Comment by GuoMeng6** [comment]
作者不用看了，我 clone 了当前的项目以及用了纯净的 RN0.72 跑 demo 发现键盘都是正常的，我再排查下当前项目有啥额外特殊的处理
