### ISSUE TITLE
native-stack react-navigation go back using the nestedScrolview causing a crash

### ISSUE THREAD

**Issue by hamdij0maa** [sdcxtech/react-native-troika#6]
<NestedScrollView/> inside a native-stack from react-navigation, causing a crash on only Android when you push 2 screen in top of each other and contains a <NestedScrollView/> component

**Comment by listenzz** [comment]
Can you provide a demo that reproduces this problem?

**Comment by hamdij0maa** [comment]
i'll do when I have some free time, but basically this is the structure : 

const Tabs = createBottomTabsNavigator()
const TabsScreen = ()=>{
return(
<Tabs.Navigator>
   <Tabs.Screen name="tabs" component={TabsScreen}/>
<Tabs.Navigator/>
)
}

const AppStack = createNativeStackNavigtor()
<AppStack.Navigator>
<AppStack.Screen name="TabsScreen" component={TabsScreen}/>
<AppStack.Screen name="ScreenOne" component={ScreenOne}/>
<AppStack.Screen name="ScreenTwo" component={ScreenTwo}/>
</AppStack.Navigator/>

when you navigate from  TabsScreen to ScreenOne => OK 
when you go from TabsScreen to screenOne To Screen two, then you go back to tabs the app crashs. 
I checked and sure that the problem is caused by NestedScrollView component 
only on android

**Comment by listenzz** [comment]
Is `NestedScrollView` in TabsScreen?

**Comment by hamdij0maa** [comment]
no nestedScrollView is inside <AppStack.Screen name="ScreenOne" component={ScreenOne}/>

**Comment by listenzz** [comment]
`NestedScrollView` inside TabsScreen and ScreenTwo?

**Comment by hamdij0maa** [comment]
no : NestedScrollView inside ScreenOne
but also:
I am using the :import {RefreshControl} from '@sdcx/pull-to-refresh'; inside : ScreenTwo

**Comment by hamdij0maa** [comment]
here is the full return code inside of the screenOne  ( stack pushed over the tabs )
<Box flex={1} backgroundColor="screenBackground">
      <UserProfileHeader user={updatedUser} />
      <PullToRefresh
        style={globalStyles.flexOne}
        refreshing={isRefreshing}
        onRefresh={refreshHandler}>
        <NestedScrollView
          bounces={false}
          style={globalStyles.nestedScrollViewContainer}>
          <NestedScrollViewHeader stickyHeaderBeginIndex={1}>
            <UserProfileTabBar
              isLoadingNotify={isLoadingNotify}
              handleNotifyMe={handleNotifyMe}
              onDeclineFollow={handleDecline}
              isLoadingDecline={isLoadingDecline}
              isLoadingFollowing={isLoadingFollowing}
              followButtonType={followButtonType}
              handleFollowing={handleFollowing}
              isLoading={loading || !called}
              user={updatedUser}
            />

            {(Boolean(!updatedUser?.followed) &&
              updatedUser?.setting?.private_profile) ||
            updatedUser?.blocked ? null : (
              <UserTabs
                pageRef={pageRef}
                listArray={[
                  {
                    index: 0,
                    title: t('profile-tabs-posts')?.toString(),
                  },
                  {
                    index: 1,
                    title: t('profile-tabs-supported')?.toString(),
                  },
                  {
                    index: 2,
                    title: t('profile-tabs-about')?.toString(),
                  },
                ]}
                isLoading={loading || !called}
                activeIndex={activeTabIndex}
              />
            )}
          </NestedScrollViewHeader>

          {updatedUser && updatedUser?.blocked ? null : (
            <PrivateAccountInfo
              isPrivate={
                Boolean(!updatedUser?.followed) &&
                updatedUser?.setting?.private_profile
              }
            />
          )}
          <BlockedHandlerUserProfile
            user_id={params?.user?.id}
            blocked={updatedUser && updatedUser?.blocked}
          />
          {(Boolean(!updatedUser?.followed) &&
            updatedUser?.setting?.private_profile) ||
          updatedUser?.blocked ? null : (
            <Box
              flex={1}
              minHeight={SIZES.screenHeight - HEADER_PROFILE_HEIGHT}>
              <PagerView
                layoutDirection="ltr"
                initialPage={0}
                ref={pageRef}
                onPageSelected={onPageSelected.current}
                style={globalStyles.pagerViewSceneContainerStyle}
                orientation="horizontal">
                <UserProfilePostsList
                  navigation={navigation}
                  isLoadingUser={loading}
                  isFocused={activeTabIndex === 0 && !isPending}
                  userId={params?.user?.id?.toString() + ''}
                />
                <UserProfileSupportedPostsList
                  navigation={navigation}
                  isLoadingUser={loading}
                  isFocused={activeTabIndex === 1 && !isPending}
                  userId={params?.user?.id?.toString() + ''}
                />
                <ProfileAboutTab
                  isFocused={activeTabIndex === 2 && !isPending}
                  isLoading={loading}
                  isRefreshing={isRefreshing}
                  user={updatedUser}
                />
              </PagerView>
            </Box>
          )}
        </NestedScrollView>
      </PullToRefresh>
    </Box>

**Comment by hamdij0maa** [comment]
the problem:
the second screen contains this library custom refreshControl
when removing it the problem fixed

**Comment by listenzz** [comment]
try the 0.4.0 version

**Comment by hamdij0maa** [comment]
works, thank you!

**Comment by chj-damon** [comment]
@listenzz what have you changed in the code? I didn't see any code update in the commits

**Comment by listenzz** [comment]
<img width="1138" alt="image" src="https://github.com/sdcxtech/react-native-troika/assets/4386370/298e0b98-b951-4ee0-9bc6-2f1fce3d1e0a">

This is an issue that has been fixed and somehow not released to the correct version. I just re-release a version.
