### ISSUE TITLE
nestedscrollview - ios全面屏手机如果底部有tab栏，则会挡住

### ISSUE THREAD

**Issue by JamesWangccc23** [sdcxtech/react-native-troika#8]
目测应该没有考虑tab栏，直接按照屏幕高度计算的？安卓不存在这个问题

**Comment by listenzz** [comment]
并不会锁定高度，它是由样式表决定的。

我们看一下你说的这种情况。

**Comment by listenzz** [comment]
你使用的导航组件是 react-navigation 吗，经过我们测试，未能发现你说的问题。

**Comment by listenzz** [comment]
相关代码可以查看 https://github.com/listenzz/RNDemo/tree/tabs

**Comment by JamesWangccc23** [comment]
> 相关代码可以查看 https://github.com/listenzz/RNDemo/tree/tabs

需要手动设置高度吗，我是套在一个flex:1的view里

**Comment by JamesWangccc23** [comment]
`<View style={{ flex: 1, overflow: 'hidden' }}>
        <PullToRefresh refreshing={refreshing} onRefresh={() => {
          setRefreshing(true)
          refresh()
          refreshTimer.current = setTimeout(() => {
            console.log('超时关闭')
            setRefreshing(false)
          }, 2500);
        }} style={{  }}>
          <NestedScrollView>
            <NestedScrollViewHeader onScroll={e => {
              showbg2.value = e.nativeEvent.contentOffset.y >= headerHeightValue - .5
            }}>
              <View style={{ height: headerHeightValue }}>
                {header}
              </View>
            </NestedScrollViewHeader>
            <DMTabView navigation={props.navigation}></DMTabView>
          </NestedScrollView>
        </PullToRefresh>
      </View>`

**Comment by JamesWangccc23** [comment]
```
<View style={{ flex: 1, overflow: 'hidden' }}>
        <PullToRefresh refreshing={refreshing} onRefresh={() => {
          setRefreshing(true)
          refresh()
          refreshTimer.current = setTimeout(() => {
            console.log('超时关闭')
            setRefreshing(false)
          }, 2500);
        }} style={{  }}>
          <NestedScrollView>
            <NestedScrollViewHeader onScroll={e => {
              showbg2.value = e.nativeEvent.contentOffset.y >= headerHeightValue - .5
            }}>
              <View style={{ height: headerHeightValue }}>
                {header}
              </View>
            </NestedScrollViewHeader>
            <DMTabView navigation={props.navigation}></DMTabView>
          </NestedScrollView>
        </PullToRefresh>
      </View>
```

**Comment by JamesWangccc23** [comment]
> 你使用的导航组件是 react-navigation 吗，经过我们测试，未能发现你说的问题。

是的 6.x

**Comment by JamesWangccc23** [comment]
> 你使用的导航组件是 react-navigation 吗，经过我们测试，未能发现你说的问题。

可能我描述的不够准确，是scroll拉到底部，然后有一部分底部内容会被底部tab挡住

**Comment by JamesWangccc23** [comment]
需要手动设置一个比较大的paddingbottom

**Comment by listenzz** [comment]
> > 你使用的导航组件是 react-navigation 吗，经过我们测试，未能发现你说的问题。
> 
> 可能我描述的不够准确，是scroll拉到底部，然后有一部分底部内容会被底部tab挡住

这种情况我们也测试了，没发现问题

**Comment by listenzz** [comment]
> > 相关代码可以查看 https://github.com/listenzz/RNDemo/tree/tabs
> 
> 需要手动设置高度吗，我是套在一个flex:1的view里

PullToRefresh 有一个默认样式 `{ flex: 1 }`，NestedScrollView 没有默认样式，需要自行设置 `{ flex: 1 }`

**Comment by listenzz** [comment]
> ```
> <View style={{ flex: 1, overflow: 'hidden' }}>
>         <PullToRefresh refreshing={refreshing} onRefresh={() => {
>           setRefreshing(true)
>           refresh()
>           refreshTimer.current = setTimeout(() => {
>             console.log('超时关闭')
>             setRefreshing(false)
>           }, 2500);
>         }} style={{  }}>
>           <NestedScrollView>
>             <NestedScrollViewHeader onScroll={e => {
>               showbg2.value = e.nativeEvent.contentOffset.y >= headerHeightValue - .5
>             }}>
>               <View style={{ height: headerHeightValue }}>
>                 {header}
>               </View>
>             </NestedScrollViewHeader>
>             <DMTabView navigation={props.navigation}></DMTabView>
>           </NestedScrollView>
>         </PullToRefresh>
>       </View>
> ```

留意到你们在代码里面使用了 TabView，我们的测试代码也更新为了 TabView，希望对你们排查问题有所帮助。

**Comment by JamesWangccc23** [comment]
> > > 相关代码可以查看 https://github.com/listenzz/RNDemo/tree/tabs
> > 
> > 
> > 需要手动设置高度吗，我是套在一个flex:1的view里
> 
> PullToRefresh 有一个默认样式 `{ flex: 1 }`，NestedScrollView 没有默认样式，需要自行设置 `{ flex: 1 }`

设置flex:1就可以了，谢谢！

**Comment by JamesWangccc23** [comment]
> > > 相关代码可以查看 https://github.com/listenzz/RNDemo/tree/tabs
> > 
> > 
> > 需要手动设置高度吗，我是套在一个flex:1的view里
> 
> PullToRefresh 有一个默认样式 `{ flex: 1 }`，NestedScrollView 没有默认样式，需要自行设置 `{ flex: 1 }`

还有个问题，用非全面屏ios手机header高度大概为1000左右时，设置外层scroll style为flex:1，会导致外层scroll拉动距离缩小，拉到底，需要利用ios的弹性再拉一段才能到内层scroll，你可以试下，不设置flex:1，可以拉到内层scroll，但是底部会被遮挡，测试手机：6s plus

**Comment by JamesWangccc23** [comment]
知道原因了，`<View style={{ height: headerHeightValue }}>` headerHeightValue 的 state 变化了两次，只取了第一次

**Comment by listenzz** [comment]
> 知道原因了，`<View style={{ height: headerHeightValue }}>` headerHeightValue 的 state 变化了两次，只取了第一次

是 NestedScrollVeiw 感知不到高度发生了变化吗？还是你那边处理就好了？

**Comment by JamesWangccc23** [comment]
> > 知道原因了，`<View style={{ height: headerHeightValue }}>` headerHeightValue 的 state 变化了两次，只取了第一次
> 
> 是 NestedScrollVeiw 感知不到高度发生了变化吗？还是你那边处理就好了？

高版本iphone可以感知到，低版本比如我手上的6sp只能取初始高度

**Comment by listenzz** [comment]
升级到  @sdcx/nested-scroll 到 0.6.0 试试

**Comment by JamesWangccc23** [comment]
> 升级到 @sdcx/nested-scroll 到 0.6.0 试试

ok的，只要初始值不为0，都可以，非常感谢！

**Comment by listenzz** [comment]
> > 升级到 @sdcx/nested-scroll 到 0.6.0 试试
> 
> ok的，只要初始值不为0，都可以，非常感谢！

升级到 0.6.0 后，初始值为 0，不可以吗？

**Comment by JamesWangccc23** [comment]
> > > 升级到 @sdcx/nested-scroll 到 0.6.0 试试
> > 
> > 
> > ok的，只要初始值不为0，都可以，非常感谢！
> 
> 升级到 0.6.0 后，初始值为 0，不可以吗？

是的，初始值为1就可以变化，为0的话就是0了，对我来说影响不大，因为我会默认给一个初始值

**Comment by listenzz** [comment]
NestedScrollViewHeader 的高度本身会随着内容的变化而变化，为何要自己计算高度？

**Comment by JamesWangccc23** [comment]
> NestedScrollViewHeader 的高度本身会随着内容的变化而变化，为何要自己计算高度？

因为我之前没有给header设置高度，内部scroll无法滑动

**Comment by listenzz** [comment]
> > NestedScrollViewHeader 的高度本身会随着内容的变化而变化，为何要自己计算高度？
> 
> 因为我之前没有给header设置高度，内部scroll无法滑动

现在应该不需要了

**Comment by JamesWangccc23** [comment]
> > > NestedScrollViewHeader 的高度本身会随着内容的变化而变化，为何要自己计算高度？
> > 
> > 
> > 因为我之前没有给header设置高度，内部scroll无法滑动
> 
> 现在应该不需要了

刚才测试了下，去掉高度还是不可以滑动，你可以研究下，对我来说是足够了

**Comment by listenzz** [comment]
> > > > NestedScrollViewHeader 的高度本身会随着内容的变化而变化，为何要自己计算高度？
> > > 
> > > 
> > > 因为我之前没有给header设置高度，内部scroll无法滑动
> > 
> > 
> > 现在应该不需要了
> 
> 刚才测试了下，去掉高度还是不可以滑动，你可以研究下，对我来说是足够了

我研究过了，是可以滚动的。可能代码有差异，又或者你没有刷新 ios 的构建缓存。

**Comment by JamesWangccc23** [comment]
先不纠结这个问题，还有个问题就是，假如内部scroll内容比较少，拉到底部触发内部scroll以后就无法拉回去了

**Comment by JamesWangccc23** [comment]
我可以手动给他设置一个空view来占位，有没有更好的方法

**Comment by listenzz** [comment]
> 我可以手动给他设置一个空view来占位，有没有更好的方法

内部 scrollview 设置 contentContainerStyle 为 `{flexGroup: 1}`

**Comment by listenzz** [comment]
> 先不纠结这个问题，还有个问题就是，假如内部scroll内容比较少，拉到底部触发内部scroll以后就无法拉回去了

无法重现这个问题

**Comment by JamesWangccc23** [comment]
> > > > > NestedScrollViewHeader 的高度本身会随着内容的变化而变化，为何要自己计算高度？
> > > > 
> > > > 
> > > > 因为我之前没有给header设置高度，内部scroll无法滑动
> > > 
> > > 
> > > 现在应该不需要了
> > 
> > 
> > 刚才测试了下，去掉高度还是不可以滑动，你可以研究下，对我来说是足够了
> 
> 我研究过了，是可以滚动的。可能代码有差异，又或者你没有刷新 ios 的构建缓存。

今天测试了下，安卓不设置高度是可以滑动的，ios一直不行，而且安卓可能不设置高度更好一些，设置高度可能会概率重现高度变化无法识别的问题

**Comment by chj-damon** [comment]
这个问题纠结了这么久啊，直接提供一个能复现的demo，一下子就明白了

**Comment by JamesWangccc23** [comment]
> > 今天测试了下，安卓不设置高度是可以滑动的，ios一直不行，而且安卓可能不设置高度更好一些，设置高度可能会概率重现高度变化无法识别的问题
> 
> 提供一个能复现问题的 demo 给我吧

header内容通过状态改变渲染内容的同时改变高度，就会重现

**Comment by JamesWangccc23** [comment]
> > 今天测试了下，安卓不设置高度是可以滑动的，ios一直不行，而且安卓可能不设置高度更好一些，设置高度可能会概率重现高度变化无法识别的问题
> 
> 提供一个能复现问题的 demo 给我吧

```
import React, {memo, useEffect, useState} from 'react';
import type {FC} from 'react';

import {View, ScrollView, StyleSheet, Text, FlatList} from 'react-native';

import MyStatusbar from '../../component/MyStatusbar';
import MyHeader from '../../component/MyHeader';
import NavigationProps from '../../navigation/Type';
import pxToDp from '../../helper/pxToDp';
import { NestedScrollView, NestedScrollViewHeader } from '@sdcx/nested-scroll';
import helper from '../../helper/helper';
import { SceneMap, TabView } from 'react-native-tab-view';
import Buttons from './component/Buttons';
import Banner1 from './component/Banner1';
import DMTabBar from './component/DMTabBar';
import DMTabView from './component/DMTabView';

const Test: FC<NavigationProps<'Test'>> = props => {
    const renderScene = SceneMap({
        0: ()=> <FlatList nestedScrollEnabled style={{height:700}}
        data={[1,2,3,4,5]} renderItem={item=><View style={{height:700,width:pxToDp(750),backgroundColor:helper.getRandomColor()}}></View>} />,
        1: ()=> <FlatList nestedScrollEnabled style={{height:700}}
        data={[1,2,3,4,5]} renderItem={item=><View style={{height:700,width:pxToDp(750),backgroundColor:helper.getRandomColor()}}></View>} />,
        2: ()=> <FlatList nestedScrollEnabled style={{height:700}}
        data={[1,2,3,4,5]} renderItem={item=><View style={{height:700,width:pxToDp(750),backgroundColor:helper.getRandomColor()}}></View>} />,
        // 3: ()=> <Products navigation={props.navigation} ref={r=> productsRefs.current[3] = r} requestJson={{type:99, cid:1}}></Products>,
      });
      const [index, setIndex] = React.useState(0);
      const [routes] = React.useState([
        { key: '0', title: '精选' },
        // { key: '1', title: '淘宝' },
        { key: '1', title: '抖音' },
        { key: '2', title: '拼多多' },
      ]);
      const [h,setH] = useState(70)
      useEffect(()=>{
        //这一行就重现
        setH(Math.random() * 70)
      },[])
      const header = <View style={{ width: pxToDp(750), alignItems: 'center' }} onLayout={e => {
        // headerHeight.current = e.nativeEvent.layout.height;
        // setHeaderHeightValue(parseInt(String(headerHeight.current)))
        // console.log(376, "头部高", e.nativeEvent.layout.height, helper.width)
      }}>
        <Banner1 banners={[]} navigation={props.navigation}></Banner1>
        {/* 按钮组 */}
        <Buttons buttons={[]} navigation={props.navigation}></Buttons>
        <View style={{width:pxToDp(50),height:h,backgroundColor:'#ff2743'}}></View>  
      </View>
  return (
    <View style={{backgroundColor: '#f5f5f5', flex: 1}}>
        
      <MyStatusbar backgroundColor={'#fff'} dark />
      <MyHeader
        title="测试"
        backgroundColor={'#fff'}
        textColor="#333"
        navigation={props.navigation}
        backIconType={1}
      />
      <View style={{width:pxToDp(50),height:pxToDp(50)}}></View>
      <View style={{flex:1}}>
      <NestedScrollView style={{flex:1}}>
        <NestedScrollViewHeader>
            {header}
            
        </NestedScrollViewHeader>
        <DMTabView navigation={props.navigation}></DMTabView>

        
            
      </NestedScrollView>
      </View>
      
    </View>
  );
};

export default memo(Test);

const styles = StyleSheet.create({
  
});
```
这是完整的demo，我也是一步步试，试到`setH`的时候重现的

**Comment by JamesWangccc23** [comment]
> > 今天测试了下，安卓不设置高度是可以滑动的，ios一直不行，而且安卓可能不设置高度更好一些，设置高度可能会概率重现高度变化无法识别的问题
> 
> 提供一个能复现问题的 demo 给我吧

还有一个问题哈，就是你试一下安卓的内部scroll，header还没滑到顶的时候滑动内部scroll（多滑几次，滑动幅度小而快）,内部scroll会直接滑动了，这个你试一下，应该比较好重现，ios没有这个问题，估计是安卓header滑动到顶部的判断有点小问题

**Comment by listenzz** [comment]
@JamesWangccc23 给个直接能跑的 demo 吧，不然我处理起来很艰难

**Comment by JamesWangccc23** [comment]
> 还有一个问题哈，就是你试一下安卓的内部scroll，header还没滑到顶的时候滑动内部scroll（多滑几次，滑动幅度小而快）,内部scroll会直接滑动了，这个你试一下，应该比较好重现，ios没有这个问题，估计是安卓header滑动到顶部的判断有点小问题

@listenzz 可以先看下这个问题吗，比较着急

**Comment by listenzz** [comment]
> > 还有一个问题哈，就是你试一下安卓的内部scroll，header还没滑到顶的时候滑动内部scroll（多滑几次，滑动幅度小而快）,内部scroll会直接滑动了，这个你试一下，应该比较好重现，ios没有这个问题，估计是安卓header滑动到顶部的判断有点小问题
> 
> @listenzz 可以先看下这个问题吗，比较着急

你在 `NestedScrollView` 下面增加如下代码，看下效果：

```java
    @Override
    public boolean onNestedPreFling(View target, float velocityX, float velocityY) {
        boolean consumed = super.onNestedPreFling(target, velocityX, velocityY);
        if (velocityY > 0 && canScrollVertically(1)) {
            return true;
        }
        return consumed;
    }
```

**Comment by JamesWangccc23** [comment]
> > > 还有一个问题哈，就是你试一下安卓的内部scroll，header还没滑到顶的时候滑动内部scroll（多滑几次，滑动幅度小而快）,内部scroll会直接滑动了，这个你试一下，应该比较好重现，ios没有这个问题，估计是安卓header滑动到顶部的判断有点小问题
> > 
> > 
> > @listenzz 可以先看下这个问题吗，比较着急
> 
> 你在 `NestedScrollView` 下面增加如下代码，看下效果：
> 
> ```java
>     @Override
>     public boolean onNestedPreFling(View target, float velocityX, float velocityY) {
>         boolean consumed = super.onNestedPreFling(target, velocityX, velocityY);
>         if (velocityY > 0 && canScrollVertically(1)) {
>             return true;
>         }
>         return consumed;
>     }
> ```

厉害，几行代码解决问题，目前没有重现

**Comment by listenzz** [comment]
[RNDemo.zip](https://github.com/sdcxtech/react-native-troika/files/12417917/RNDemo.zip)

**Comment by listenzz** [comment]
@JamesWangccc23 我发给你的 demo 可以在 iPhone 14 Pro 模拟器上重现你说的问题，初步判断为 objc 浮点数大小比较不准确问题。

**Comment by listenzz** [comment]
@JamesWangccc23 升级到 0.8.0，已处理浮点数大小比较问题。

**Comment by JamesWangccc23** [comment]
> @JamesWangccc23 升级到 0.8.0，已处理浮点数大小比较问题。

厉害
